name: device_info_plus_web
description: An implementation for the web platform of the Flutter `device_info_plus` plugin.
version: 0.3.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      web:
        pluginClass: DeviceInfoPlusPlugin
        fileName: device_info_plus_web.dart

dependencies:
  device_info_plus_platform_interface: ^0.3.0
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  test: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^4.1.2
  pedantic: ^1.9.2

environment:
  sdk: '>=2.12.0-0'
  flutter: '>=1.20.0'
